api = "0.2"

[buildpack]
  id = "{{ .organization }}/{{ .buildpack }}"
  name = "{{ .buildpack | Title }} Buildpack"
  version = "0.0.2"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[metadata]
  include_files = ["bin/build","bin/detect","buildpack.toml"]
  pre_package = "./scripts/build.sh"
